name: algostun_auto_commit
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '**.c'
      - '**.cpp'
      - '**.java'
  workflow_dispatch:

env:
  NICKNAME: bmincof
  EMAIL: bminlvcoffee@gmail.com
  REPOSITORY: Algorithms

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: bmincof/algostun-auto-commit
          ref: develop
          token: ${{ secrets.ACTIONS_KEY }}
      - run: ls

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python scripts/main.py ${{ secrets.ACTIONS_KEY }} ${{ env.NICKNAME }} ${{ env.EMAIL }} ${{ env.REPOSITORY }}
